[[redirects]]
  from = "/stats.js"
  to = "https://cloud.umami.is/script.js"
  status = 200

[[redirects]]
  from = "/tools"
  to = "/tools/ics-generator"
  status = 302

[[redirects]]
  from = "/tools/*"
  to = "https://luhive-tools.netlify.app/:splat"
  status = 200
  force = true

[build]
  command = "react-router build"
  publish = "build/client"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "build/client,build/server"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL,SUPABASE_ANON_KEY,VITE_GOOGLE_MAPS_API_KEY"