/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type EventApprovalStatuses = "approved" | "pending" | "rejected";

export type EventStatus = "cancelled" | "draft" | "published";

export type EventType = "hybrid" | "in-person" | "online";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type ReminderTime = "1-day" | "1-hour" | "3-days" | "3-hours" | "5-days" | "5-hours";

export type RsvpStatus = "going" | "maybe" | "not_going";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AnnouncementViews {
  announcement_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  session_id: string | null;
  user_id: string | null;
  view_source: string;
}

export interface ApiKeys {
  allowed_origins: Generated<string[]>;
  community_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  key_hash: string;
  key_id: string;
  key_kind: Generated<string>;
  key_type: string;
  last_used_at: Timestamp | null;
  name: string;
  revoked_at: Timestamp | null;
  scopes: Generated<string[]>;
}

export interface Communities {
  cover_url: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string;
  description: string | null;
  id: Generated<string>;
  /**
   * for front to show community on hub or not
   */
  is_show: Generated<boolean>;
  logo_url: string | null;
  name: string;
  page_config: Generated<Json | null>;
  parent_community_id: string | null;
  settings: Generated<Json | null>;
  slug: string;
  social_links: Json | null;
  stats: Generated<Json | null>;
  tagline: string | null;
  tracking_enabled: Generated<boolean>;
  updated_at: Generated<Timestamp | null>;
  verified: Generated<boolean | null>;
}

export interface CommunityAnnouncementImages {
  announcement_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  image_url: string;
  sort_order: Generated<number>;
  storage_path: string | null;
}

export interface CommunityAnnouncements {
  community_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string;
  email_sent_at: Timestamp | null;
  id: Generated<string>;
  published: Generated<boolean>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface CommunityMembers {
  community_id: string | null;
  custom_title: string | null;
  email_opt_out: Generated<boolean>;
  id: Generated<string>;
  joined_at: Generated<Timestamp | null>;
  metadata: Generated<Json | null>;
  notify_registrations: Generated<boolean>;
  role: Generated<string | null>;
  user_id: string | null;
}

export interface CommunityVisits {
  community_id: string | null;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  session_id: string;
  user_id: string | null;
  visited_at: Generated<Timestamp | null>;
}

export interface EventCollaborations {
  accepted_at: Timestamp | null;
  community_id: string;
  created_at: Generated<Timestamp | null>;
  event_id: string;
  id: Generated<string>;
  invited_at: Generated<Timestamp>;
  invited_by: string;
  role: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface EventRegistrations {
  anonymous_email: string | null;
  anonymous_name: string | null;
  anonymous_phone: string | null;
  approval_status: EventApprovalStatuses | null;
  attended_at: Timestamp | null;
  checkin_token: string | null;
  /**
   * Stores user answers to custom questions
   */
  custom_answers: Generated<Json | null>;
  event_id: string;
  id: Generated<string>;
  invited_by_user_id: string | null;
  is_attended: Generated<boolean>;
  is_verified: Generated<boolean>;
  registered_at: Generated<Timestamp | null>;
  registration_city: string | null;
  registration_country: string | null;
  registration_ip: string | null;
  registration_session_id: string | null;
  registration_source_community_id: string | null;
  registration_type: Generated<string>;
  rsvp_status: Generated<RsvpStatus>;
  time_to_register_seconds: number | null;
  token_expires_at: Timestamp | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
  utm_campaign: string | null;
  utm_content: string | null;
  utm_medium: string | null;
  utm_source: string | null;
  utm_term: string | null;
  verification_token: string | null;
}

export interface EventReminders {
  created_at: Generated<Timestamp | null>;
  custom_message: string | null;
  event_id: string;
  id: Generated<string>;
  reminder_times: Generated<ArrayType<ReminderTime>>;
  updated_at: Generated<Timestamp | null>;
}

export interface Events {
  capacity: number | null;
  community_id: string;
  cover_url: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string;
  currency: Generated<string>;
  /**
   * Stores custom registration questions configuration
   */
  custom_questions: Generated<Json | null>;
  description: string | null;
  discussion_link: string | null;
  end_time: Timestamp | null;
  event_type: EventType;
  /**
   * Which external platform is used
   */
  external_platform: string | null;
  /**
   * Manually tracked registration count from external platform
   */
  external_registration_count: Generated<number | null>;
  /**
   * URL to external registration form
   */
  external_registration_url: string | null;
  id: Generated<string>;
  is_approve_required: Generated<boolean>;
  /**
   * Formatted address from Google Places
   */
  location_address: string | null;
  /**
   * Latitude from Google Places
   */
  location_lat: number | null;
  /**
   * Longitude from Google Places
   */
  location_lng: number | null;
  /**
   * Venue or place name from Google Places
   */
  location_name: string | null;
  /**
   * Google Place ID for deep links and embed
   */
  location_place_id: string | null;
  online_meeting_link: string | null;
  /**
   * Ticket price in minor units (qəpik). NULL means the event is free.
   */
  price_minor: number | null;
  registration_deadline: Timestamp | null;
  /**
   * Where users can register: native (Luhive), external (Google Forms etc), or both
   */
  registration_type: Generated<string | null>;
  /**
   * URL-friendly slug for public event pages
   */
  slug: string;
  start_time: Timestamp;
  status: Generated<EventStatus>;
  timezone: string;
  title: string;
  updated_at: Generated<Timestamp | null>;
}

export interface EventVisits {
  browser: string | null;
  city: string | null;
  community_id: string;
  country: string | null;
  created_at: Generated<Timestamp>;
  device_type: string | null;
  event_id: string;
  id: Generated<string>;
  ip: string | null;
  is_mobile: boolean | null;
  os: string | null;
  referrer_domain: string | null;
  referrer_url: string | null;
  region: string | null;
  session_id: string;
  timezone: string | null;
  user_id: string | null;
  utm_campaign: string | null;
  utm_content: string | null;
  utm_medium: string | null;
  utm_source: string | null;
  utm_term: string | null;
  visited_at: Generated<Timestamp>;
}

export interface GoogleFormsTokens {
  access_token: string;
  created_at: Generated<Timestamp | null>;
  expiry_date: Timestamp | null;
  id: Generated<string>;
  refresh_token: string | null;
  scope: string | null;
  token_type: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface HubCommunities {
  cover_url: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  description: string | null;
  event_count: Int8 | null;
  id: string | null;
  is_show: boolean | null;
  logo_url: string | null;
  member_count: Int8 | null;
  name: string | null;
  page_config: Json | null;
  parent_community_id: string | null;
  settings: Json | null;
  slug: string | null;
  social_links: Json | null;
  stats: Json | null;
  tagline: string | null;
  tracking_enabled: boolean | null;
  updated_at: Timestamp | null;
  verified: boolean | null;
}

export interface HubEvents {
  community_id: string | null;
  community_name: string | null;
  community_slug: string | null;
  cover_url: string | null;
  end_time: Timestamp | null;
  event_type: EventType | null;
  id: string | null;
  location_address: string | null;
  location_name: string | null;
  slug: string | null;
  start_time: Timestamp | null;
  timezone: string | null;
  title: string | null;
}

export interface PaymentCallbacks {
  id: Generated<string>;
  key_id: string | null;
  outcome: string;
  payload: Json;
  received_at: Generated<Timestamp>;
  registration_id: string | null;
}

export interface People {
  attributes: Generated<Json>;
  community_id: string;
  created_at: Generated<Timestamp>;
  /**
   * Soft delete. Rows are retired by stamping this, never removed.
   */
  deleted_at: Timestamp | null;
  email: string | null;
  external_id: string | null;
  id: Generated<string>;
  last_seen_at: Timestamp | null;
  locale: string | null;
  name: string | null;
  plan: string | null;
  subscription_status: string | null;
  unsubscribed_at: Timestamp | null;
}

export interface PersonEvents {
  community_id: string;
  id: Generated<string>;
  occurred_at: Generated<Timestamp>;
  person_id: string;
  properties: Generated<Json>;
  type: string;
}

export interface Profiles {
  avatar_url: string | null;
  bio: string | null;
  created_at: Generated<Timestamp | null>;
  full_name: string | null;
  gamification: Generated<Json | null>;
  id: string;
  metadata: Generated<Json | null>;
  settings: Generated<Json | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface SentReminders {
  event_id: string;
  id: Generated<string>;
  recipient_email: string;
  registration_id: string;
  reminder_time: ReminderTime;
  sent_at: Generated<Timestamp | null>;
}

export interface TelegramUsers {
  chat_id: Int8;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  telegram_id: Int8;
  user_id: string;
  username: string | null;
}

export interface TicketOrders {
  amount_minor: number;
  community_id: string;
  confirmation_email_sent_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: string;
  event_id: string;
  id: Generated<string>;
  marked_paid_by: string | null;
  paid_at: Timestamp | null;
  paid_via: string | null;
  /**
   * Checkila paymentId, stored when the payment link is created. The callback must echo it as checkilaRequestId.
   */
  partner_reference: string | null;
  payment_url: string | null;
  registration_id: string;
  status: Generated<string>;
  /**
   * Epoint transaction id from the callback, for reconciliation. NULL for manual payments.
   */
  transaction_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  announcement_views: AnnouncementViews;
  api_keys: ApiKeys;
  communities: Communities;
  community_announcement_images: CommunityAnnouncementImages;
  community_announcements: CommunityAnnouncements;
  community_members: CommunityMembers;
  community_visits: CommunityVisits;
  event_collaborations: EventCollaborations;
  event_registrations: EventRegistrations;
  event_reminders: EventReminders;
  event_visits: EventVisits;
  events: Events;
  google_forms_tokens: GoogleFormsTokens;
  hub_communities: HubCommunities;
  hub_events: HubEvents;
  payment_callbacks: PaymentCallbacks;
  people: People;
  person_events: PersonEvents;
  profiles: Profiles;
  sent_reminders: SentReminders;
  telegram_users: TelegramUsers;
  ticket_orders: TicketOrders;
}
